version: "3.8"

services:
  sonarqube:
    image: sonarqube:8.9-community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
     - db
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000

  db:
    image: postgres:13
    container_name: sonarqube_db
    restart: unless-stopped
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
    name: sonarnet

volumes:
  sonarqube_conf:
    driver: local
    name: sonarqube_conf
  sonarqube_data:
    driver: local
    name: sonarqube_data
  sonarqube_extensions:
    driver: local
    name: sonarqube_extensions
  sonarqube_bundled-plugins:
    driver: local
    name: sonarqube_bundled-plugins
  postgresql:
    driver: local
    name: sonarqube_postgresql
  postgresql_data:
    driver: local
    name: sonarqube_postgresql_data
